# Generated by Django 5.2 on 2025-05-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('SUSPENSION TEMPORAL', 'Suspensión Temporal'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20),
        ),
    ]
