# Generated by Django 5.2 on 2025-05-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='fdesde',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='fhasta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
    ]
